### ISSUE TITLE
Config cache size

### ISSUE THREAD

**Issue by hoank101** [orbitorg/core#14]
https://github.com/cosmos/cosmos-sdk/compare/v0.47.10...classic-terra:cosmos-sdk:v0.47.10-terra.1#diff-bdf0ddfb5c9ef5a689f1f22314f53f4724778508abb49f2fdc8154dcf24a75c7R65

**Comment by kien6034** [comment]
https://github.com/orbitorg/core/commit/567f5aa458e431bbda8b75d0427b4813066a8e01
