### ISSUE TITLE
[test] validator voting power limitation

### ISSUE THREAD

**Issue by kien6034** [orbitorg/core#25]
**Problem definition**
Related issue: #19 

Commit changes:
https://github.com/orbitorg/core/commit/372f6f808b344bc2b3ddac96b3edfaae7f672472

We need tests for this feature, that setup the test case to check the require to panic if  validator voting power get exceeded 20%.

Affected functions
- [ ] CreateValidator
- [ ] Delegate 
- [ ] CancelUnbondingDelegation

**Comment by tnv1** [comment]
This test is available at [`custom/staking/module_test.go`](https://github.com/classic-terra/core/blob/main/custom/staking/module_test.go). Make sure pass test with cmd:

```go
go test -v -run=TestStakingTestSuite/TestValidatorVPLimit github.com/classic-terra/core/v3/custom/staking
```

@TropicalDog17 @kien6034
